export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  smartsheetApiToken: process.env.SMARTSHEET_API_TOKEN ?? "",
  smartsheetWorkspaceId: process.env.SMARTSHEET_WORKSPACE_ID ?? "",
  smartsheetInstitutionsSheetId: process.env.SMARTSHEET_INSTITUTIONS_SHEET_ID ?? "",
  smartsheetVariablesSheetId: process.env.SMARTSHEET_VARIABLES_SHEET_ID ?? "",
  smartsheetPerformanceDataSheetId: process.env.SMARTSHEET_PERFORMANCE_DATA_SHEET_ID ?? "",
};
